name: model_interfaces
description: Common interfaces for your models that have IDs, titles, etc.
version: 0.0.4
homepage: https://github.com/alexeyinkin/dart-model-interfaces

environment:
  sdk: ">=2.12.0 <3.0.0"
